wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1652092333
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 24
      4: 3.8.10
      5: 0.12.16
      6: 4.18.0
      8:
      - 5
