---
training:
    name: "default"
    seed: 0
    lr: 0.0001
    batch_size: 1
    epochs: 10000
    num_iters: 400
dataset:
    name: "MegaMedical"
    with_replacement: True
    mid_slice_selection: True
    mid_slice_selection_min_voxels: 10
    min_support_set: 1
    max_support_set: 10
    train_dsets: []
    val_dsets: []
    train_dsets_exclude: []
    train_labels: []
    val_labels: []
    limited_dsets: []
    num_subj: -1
    pad_slices: 0
    fix_axis: -1
    include_query_chance: 0
    augs: ["rot-all", "int"]
    use_half: True
model:
    type: "SMCnoinx"
    num_feat: 128
    num_levels: 3
    num_reps: 2
    norm_schemes: ["None", "None"]
loss: 
    name: "dice"
    eps: 1
misc:
    show_output: True
    save: False

