---
experiment:
    name: "HarryPotter finetune"
    experiment_type: "HarryPotter"
    epochs: 1
    val_frequency: 2
    batchsize: 8
    model_and_task: "BrainBiasedBert HarryPotter"
dataset:
    seed: 42
    subjects: ["1", "2"]
model:
    num_out: 5
    sigmoid: False
    return_CLS_rep: False
    type: 'BrainBiasedBert'
loss: 
    name: "MSE"
misc:
    save: False

