---
experiment:
    name: "HarryPotter-finetune"
    experiment_type: "HarryPotter"
    epochs: 20
    val_frequency: 5
    batchsize: 8
    model_and_task: "BrainBiasedBert-HarryPotter"
    lr: 0.00005
dataset:
    seed: 42
    subjects: ["1"]
model:
    num_out: 5
    sigmoid: False
    return_CLS_rep: False
    type: "BrainBiasedBert"
loss: 
    name: "MSE"
misc:
    save: False

