---
experiment:
    name: "Train on telephone"
    experiment_type: "MNLI"
    epochs: 1
    val_frequency: 1
    batchsize: 8
    model_and_task: "BERT MNLI"
dataset:
    train_datasets: ["telephone"]
    val_datasets: ["telephone","letters","facetoface"]
    seed: 42
model:
    sigmoid: False
    return_CLS_rep: False
    #added type
    type: 'BERT'
loss: 
    name: 
misc:
    save: False