---
experiment:
    name: "Train on images"
    experiment_type: "STSB"
    epochs: 1
    val_frequency: 2
    batchsize: 8
    model_and_task: "BERT stsb"
dataset:
    train_datasets: ["MSRpar"]
    val_datasets: ["MSRpar","MSRvid","headlines","images"]
    limit: 1000
    seed: 42
model:
    num_out: 5
    sigmoid: False
    return_CLS_rep: False
    #added type
    type: 'BERT'
loss: 
    name: 
misc:
    save: False

