---
experiment:
    name: "Train on italian epoch 3"
    experiment_type: "Yelp"
    epochs: 20
    val_frequency: 2
    batchsize: 8
    model_and_task: "NSD Yelp"
    lr: 0.0001
dataset:
    train_datasets: ["italian"]
    val_datasets: ["american","italian","japanese","chinese"]
    limit: 1000
    seed: 42
model:
    brain_biased: True
    num_out: 5
    sigmoid: False
    return_CLS_rep: False
    #added type
    type: 'BERT'
    state_path: 'NSD_model_prime_prime_epoch_3'
loss: 
    name: 
misc:
    save: True
